version: "3"

services:
  dai-eth:
    image: ilovelili/flashloan:dai-eth
  dai-link:
    image: ilovelili/flashloan:dai-link
  dai-weth:
    image: ilovelili/flashloan:dai-weth
  dai-usdc:
    image: ilovelili/flashloan:dai-usdc
  dai-uni:
    image: ilovelili/flashloan:dai-uni
  weth-bat:
    image: ilovelili/flashloan:weth-bat
  weth-knc:
    image: ilovelili/flashloan:weth-knc
  weth-link:
    image: ilovelili/flashloan:weth-link
  weth-mkr:
    image: ilovelili/flashloan:weth-mkr
  weth-usdc:
    image: ilovelili/flashloan:weth-usdc
  weth-uni:
    image: ilovelili/flashloan:weth-uni
  
