declare const mainnet: {
    kyber: {
        kyberNetworkProxy: string;
    };
    uniswap: {
        router: string;
    };
    dydx: {
        solo: string;
    };
    tokens: {
        dai: string;
        weth: string;
        eth: string;
    };
    makerdao: {
        DEPLOYER: string;
        MULTICALL: string;
        FAUCET: string;
        MCD_DEPLOY: string;
        MCD_GOV: string;
        GOV_GUARD: string;
        MCD_ADM: string;
        MCD_VAT: string;
        MCD_JUG: string;
        MCD_CAT: string;
        MCD_VOW: string;
        MCD_JOIN_DAI: string;
        MCD_FLAP: string;
        MCD_FLOP: string;
        MCD_PAUSE: string;
        MCD_PAUSE_PROXY: string;
        MCD_GOV_ACTIONS: string;
        MCD_DAI: string;
        MCD_SPOT: string;
        MCD_POT: string;
        MCD_END: string;
        MCD_ESM: string;
        PROXY_ACTIONS: string;
        PROXY_ACTIONS_END: string;
        PROXY_ACTIONS_DSR: string;
        CDP_MANAGER: string;
        DSR_MANAGER: string;
        GET_CDPS: string;
        OSM_MOM: string;
        FLIPPER_MOM: string;
        PROXY_FACTORY: string;
        PROXY_REGISTRY: string;
        ETH: string;
        PIP_ETH: string;
        MCD_JOIN_ETH_A: string;
        MCD_FLIP_ETH_A: string;
        BAT: string;
        PIP_BAT: string;
        MCD_JOIN_BAT_A: string;
        MCD_FLIP_BAT_A: string;
        USDC: string;
        PIP_USDC: string;
        MCD_JOIN_USDC_A: string;
        MCD_FLIP_USDC_A: string;
        MCD_JOIN_USDC_B: string;
        MCD_FLIP_USDC_B: string;
        WBTC: string;
        PIP_WBTC: string;
        MCD_JOIN_WBTC_A: string;
        MCD_FLIP_WBTC_A: string;
        TUSD: string;
        PIP_TUSD: string;
        MCD_JOIN_TUSD_A: string;
        MCD_FLIP_TUSD_A: string;
        ZRX: string;
        PIP_ZRX: string;
        MCD_FLIP_ZRX_A: string;
        MCD_JOIN_ZRX_A: string;
        KNC: string;
        PIP_KNC: string;
        MCD_FLIP_KNC_A: string;
        MCD_JOIN_KNC_A: string;
        PROXY_PAUSE_ACTIONS: string;
        PROXY_DEPLOYER: string;
    };
};
export default mainnet;
